export enum NotificationAlertTypes {
  TradeTransactions = '1',
  PriceAlerts = '2',
  RealTimeAdvisoryFocusList = '3',
  DailyTechnicalSignals = '4',
  HourlyTechnicalSignals = '5',
  Research = '6',
  News = '7',
  UnusualTradingVolume = '8',
  CashDividends = '9',
  RealTimeAdvisoryResearch = '10',
  EquityResearch = '11',
  TechnicalResearch = '12',
  StrategyAndEconomy = '13',
  DailyReports = '14',
  WeeklyRTASummary = '15',
  WeeklyResearchReportsList = '16',
}
