export enum NotificationType {
  SymbolChange = 0 ,
  ExchangeChange = 1 ,
  LanguageChange ,
  ThemeChange ,
  NewsSearch ,
  FeatureSearch ,
  SelectedMyAlertChanged ,
  GlobalSearchConfigChange ,
  WidgetNavigation ,
  SnackBar ,
  SettingsIcon ,
  GMSSymbolChange ,
  SwiperSlideChanged ,
  OrderDetailsUpdated ,
  SymbolChangeOrderTicket ,
  SymbolChangeForActiveRouteOnly ,
  BackButtonPressed ,
  MiniOrderTicketSymbolSearch ,
  SelectedWatchlistOption ,
  MubasherStoreSymbolChange ,
}
