export enum TradingRuleTypes {
	Tif = '1',
	OrderSide = '2',
	OrderType = '3',
	DisclosureBenchmark = 'DISCLOSURE_BENCHMARK',
	ValDisclosureQty = 'VAL_DISCLOSURE_QTY',
	Amend =  'AMEND',
	Cancel = 'CANCEL',
	MiniOrderTypes = 'MINI_ORDER_TYPES',
	DefOrderType = 'DEF_ORDER_TYPE',
	DefTif = 'DEF_TIF',
	OrderTypeTif =  'ORDER_TYPE_TIF',
	AmendOrderTypes = 'AMEND_ORDER_TYPES',
	AmendTif = 'AMEND_TIF',
	AmendFields = 'AMEND_FIELDS',
	AmendPriceDisableOrderTypes = 'AMEND_PRICE_DISABLE_ORDER_TYPES',
	DwCancel = 'DW_CANCEL',
	AonDisabled = 'AON_DISABLED',
	AonEnabled = 'AON_ENABLED',
	TradingSessionDetails = 'PRE_POST_SESSION_TRADING',
}
