export enum WidgetTypes {
  home = "home",
  scope = "scope",
  policy = "policy",
  training = "training",
  tracibility = "tracibility",
  StockProfile = "stockProfile",
  OneStopTrade = "oneStopTrade",
  Portfolio = "portfolio",
  DocumentControl = "documentControl",
  TopLevelManuals = "topLevelManuals",
  WorkInstructions = "workInstructions",
  Records = "records",
  Procedures = "procedures",
  ChangeDocumentOrRecord = "changeDocOrRec",
  DocOrRecReviewUpdateProcess = "docOrRecRevUpProcess",
  Reports = "reports",
  AddMrmMeeting = "addMrmMeeting",
  ComplainNote = "complainNote",
  Process = "process",
  Store = "store",
  WorkSheet = "workSheet",
  Supplier = "supplier",
  FinalStore = "finalStore",
  FinalWorkSheet = "finalWorkSheet",
}
