export enum InquiryRequestTypes {
  BuyingPower = 1 ,
  Portfolio ,
  CustomerBankList ,
  BankList ,
  MarginableSymbolList ,
  ExchangeLevelConfig = 9 ,
  RuleList = 13 ,
  FuturePortfolio = 20 ,
  OptionPortfolio ,
  MasterData = 24 ,
  CFDPortfolio = 30 ,
  FundPortfolio = 32 ,
  ServiceNotification ,
  ServiceNotificationFeedback ,
  TransactionSummary = 35 ,
  BestTrades ,
  WorstTrades ,
  PerformanceChart = 38 ,
  PerformanceRatio ,
  CustomerInformation ,
  SpotPortfolio = 41 ,
  AutoTradeMasterData ,
  AutoTradePositions ,
  WealthPortfolioInvestment = 45 ,
  WealthPortfolioWealthManagement = 46 ,
}
