export enum InquiryResponseTypes {
  BuyingPower = 101,
  Portfolio,
  CustBankList,
  BankList = 104,
  MarginableSymbolList,
  ExchangeLevelConfig = 109,
  OrderList = 112,
  RuleList,
  FuturePortfolio = 120,
  MasterData = 124,
  CFDPortfolio = 130,
  FundPortfolio = 132,
  ServiceNotification,
  ServiceNotificationFeedback,
  TransactionSummary = 135,
  BestTrades,
  WorstTrades,
  PerformanceChart = 138,
  PerformanceRatio,
  CustomerInformation,
  SpotPortfolio = 141,
  AutoTradeMasterData,
  AutoTradePositions,
  WealthPortfolioInvestment = 145,
  WealthPortfolioWealthManagement = 146,
  UnsolicitedBuyingPower = 201,
  UnsolicitedRequestCancel = 204,
}
