export enum OrderSubmissionTypes {
  NormalOrder = 1,
  ConditionalOrder,
  CancelOrder,
  AmendOrder,
  BracketOrder,
  FuturesOrder,
  AmendFuturesOrder,
  CancelFuturesOrder,
  CFDOrder,
  AmendCFDOrder,
  CancelCFDOrder,
  SpotOrder,
  AmendSpotOrder,
  CancelSpotOrder,
}
