export enum TIFTypes {
  DAY_ORDER = 0,
  GOOD_TILL_CANCEL,
  AT_THE_OPENING,
  IMMEDIATE_OR_CANCEL,
  FILL_OR_KILL,
  GOOD_TILL_CROSSING,
  GOOD_TILL_DATE,
  AT_THE_CLOSING,
  MONTH,
  SESSION,
  SESSION_1 = 101,
  SESSION_2,
}
